wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1725000275
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 53
      - 55
      - 80
      3:
      - 2
      - 23
      - 37
      4: 3.12.4
      5: 0.17.8
      8:
      - 1
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 0.0017093793001178848
